
AWSTemplateFormatVersion: "2010-09-09"
Description: 
  "Cloud stack with a lambda function that runs AutoMorph images uploaded into an s3 bucket"
Globals:
  Function:
    Timeout: 240
    MemorySize: 3008 
  Api:
    OpenApiVersion: 3.0.1
Parameters:
  Stage:
    Type: String
    Default: dev

Transform: AWS::Serverless-2016-10-31

Resources:
  SourceBucket:
    Type: AWS::S3::Bucket
  AutomorphFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            SourceArn: 'arn:aws:s3:::automorph-lambda-buckets'
            Events:
              - 's3:ObjectCreated:*' 
      Policies:
        AWSLambdaExecute
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./
      DockerTag: image_automorph-v1
