
AWSTemplateFormatVersion: "2010-09-09"
Description: 
  "Test for automorph lambda function"
Globals:
  Function:
    Timeout: 240
    MemorySize: 3008 
  Api:
    OpenApiVersion: 3.0.1
Parameters:
  Stage:
    Type: String
    Default: dev

Transform: AWS::Serverless-2016-10-31

Resources:
  # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
  SourceImageBucket:
    Type: 'AWS::S3::Bucket'
#    DeletionPolicy: Retain
#    Properties:
#      BucketName: 'automorph-lambda-buckets'
  # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  AutomorphFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: SourceImageBucket
            Events:
              - 's3:ObjectCreated:*' 
      Policies:
        AWSLambdaExecute
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./
      DockerTag: image_automorph-v1

#  EventObjectUpload:
#    Type: AWS::Events::Rule
#    Properties:
#      Description: "Approved transactions"
#      EventPattern:
#        source:
#          - "custom.myATMapp"
#        detail-type:
#          - transaction
#        detail:
#          result:
#            - "approved"
#      State: "ENABLED"
#      Targets:
#        -
#          Arn:
#            Fn:GetAtt:
#              - "AutomorphFunction"
#              - "Arn"
#          Id: "AutomorphImageUpld"
#
#  PermissionForEventsToInvokeLambda: 
#    Type: AWS::Lambda::Permission
#    Properties: 
#      FunctionName: 
#        Ref: "AutomorphImageUpld"
#      Action: "lambda:InvokeFunction"
#      Principal: "events.amazonaws.com"
#      SourceArn: 
#        Fn::GetAtt: 
#          - "EventRuleCase1"
#          - "Arn"